v0.0.0_67

diff --git a/template/gnostr-send b/template/gnostr-send
--- a/template/gnostr-send
+++ b/template/gnostr-send
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
-NOSTR_RELAYER=${NOSTR_RELAYER:-nostcat}
+GNOSTR_RELAYER=${GNOSTR_RELAYER:-gnostr-cat}
 
-if ! command -v $NOSTR_RELAYER >&2 >/dev/null; then
-	printf "error: nostr relayer '%s' not found, set \$NOSTR_RELAYER or install '%s'\n" $NOSTR_RELAYER $NOSTR_RELAYER
+if ! command -v $GNOSTR_RELAYER >&2 >/dev/null; then
+	printf "error: gnostr relayer '%s' not found, set \$GNOSTR_RELAYER or install '%s'\n" $GNOSTR_RELAYER $GNOSTR_RELAYER
 	exit 1
 fi
 
 usage() {
-	printf "usage: git-send-nostr [OPTIONS...] <commit> [NOSTRIL OPTIONS...]\n\n"
+	printf "usage: gnostr send [OPTIONS...] <commit> [GNOSTR OPTIONS...]\n\n"
 
 	printf "OPTIONS\n\n"
-	printf "     -r            Relay to broadcast to. Will use 'git config nostr.relays' by default\n"
+	printf "     -r            Relay to broadcast to. Will use 'git config gnostr.relays' by default\n"
 	printf "     -d            Dry run. Just print event to stdout instead of relaying.\n"
 	printf "\n"
-	printf "     any other nostril option is supported here:\n\n"
-	printf "NOSTRIL OPTIONS\n"
-	nostril | sed '1,/OPTIONS/d'
+	printf "     any other gnostr option is supported here:\n\n"
+	printf "GNOSTR OPTIONS\n"
+	gnostr | sed '1,/OPTIONS/d'
 	printf "\nEXAMPLES\n\n"
-	printf "git send-nostr -d HEAD^- -t nostril -t nostrildev --pow 15\n\n"
+	printf "gnostr-send -d HEAD^- -t gnostr -t gnostr_dev --pow 15\n\n"
 	exit 0
 }
 
@@ -42,7 +42,7 @@ shift $((OPTIND-1))
 
 
 if [ -z $relay ]; then
-	relay=$(git config nostr.relays)
+	relay=$(git config gnostr.relays)
 	if [[ $relay == "" ]]; then
 		unset relay
 	fi
@@ -57,15 +57,15 @@ commit=$1
 shift
 
 # this can be overridden
-sec="$(git config nostr.secretkey)"
+sec="$(gnostr-git config gnostr.secretkey)"
 if [[ $sec != "" ]]; then
 	sec="--sec $sec"
 fi
 
-patch="$(git format-patch --stdout $commit)"
+patch="$(gnostr-git format-patch --stdout $commit)"
 subject=$(<<<"$patch" grep "^Subject:"| head -n1 | sed 's,^Subject: ,,')
 author=$(<<<"$patch" grep "^From:"| head -n1 | sed 's,^From: ,,')
-json=$(nostril --envelope $sec --kind 19691228 --tag author "$author" --tag subject "$subject" --content "$patch" "$@")
+json=$(gnostr --envelope $sec --kind 19691228 --tag author "$author" --tag subject "$subject" --content "$patch" "$@")
 
 id=$(jq -r '.[1].id' <<<"$json")
 
@@ -74,7 +74,7 @@ if [ -n "$dryrun" ]; then
 	printf "\nDRY RUN. printing event data\n" >&2
 elif [ -z "$relay" ]; then
 	echo "$json"
-	printf "\nRELAY NOT SET, not relaying. Use -r wss://relay.damus.io or 'git config --global nostr.relays wss://relay.damus.io'\n" >&2
+	printf "\nRELAY NOT SET, not relaying. Use -r wss://relay.damus.io or 'git config --global gnostr.relays wss://relay.damus.io'\n" >&2
 else
 	echo "$id"
 	printf "relaying to $relay using $NOSTR_RELAYER...\n" >&2
@@ -82,5 +82,5 @@ else
 fi
 
 if [[ $sec == "" ]]; then
-	printf "NOSTR SECRET KEY NOT SET, using random key. Use --sec <key> or 'git config --global nostr.secretkey <hexkey>'\n" >&2
+	printf "NOSTR SECRET KEY NOT SET, using random key. Use --sec <key> or 'git config --global gnostr.secretkey <hexkey>'\n" >&2
 fi
